using Assets.Scripts.SystemAI;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// This class is responsible og taking care of messaging the AI if it can operate again,
/// it holds a counter of objects generated by the AI and counts down, when it reaches 0 it lets
/// the AI know.
/// </summary>
public class CountDownRoot
{
    private int numOfChildren;
    Action mCallback;

    public CountDownRoot(Action callback)
    {
        this.numOfChildren = 0;
        mCallback = callback;
    }

    public void IncreaseByOne()
    {
        //Debug.Log("CountDownRoot: IncreaseByOne");
        numOfChildren++;
       //Debug.Log("CountDownRoot: IncreaseByOne " + numOfChildren);
    }

    public void DecreaseByOne()
    {
        //Debug.Log("CountDownRoot: DecreaseByOne");

        numOfChildren--;

        //Debug.Log("CountDownRoot: DecreaseByOne " + numOfChildren);
        ShouldDestroy();
    }

    void ShouldDestroy()
    {


        if (numOfChildren == 0)
        {
            //Debug.Log("CountDownRoot: ShouldDestroy");


            mCallback();
        }
    }


}
